export const postalCodes = [
	{ abbrev: "AF", regex: "/[0-9]{4}/" },
	{ abbrev: "AL", regex: "/(120|122)[0-9]{2}/" },
	{ abbrev: "DZ", regex: "/[0-9]{5}/" },
	{ abbrev: "AS", regex: "/[0-9]{5}/" },
	{ abbrev: "AD", regex: "/[0-9]{5}/" },
	{ abbrev: "AO", regex: "/^d{5}$/" },
	{ abbrev: "AI", regex: "/AI-2640/" },
	{ abbrev: "AG", regex: "/d{5}(?:[-s]d{4})?/" },
	{ abbrev: "AR", regex: "/[A-Z]{1}[0-9]{4}[A-Z]{3}/" },
	{ abbrev: "AM", regex: "/[0-9]{4}/" },
	{ abbrev: "AW", regex: "/^d{5}$/" },
	{ abbrev: "AU", regex: "/[0-9]{4}/" },
	{ abbrev: "AT", regex: "/[0-9]{4}/" },
	{ abbrev: "AZ", regex: "/[0-9]{4}/" },
	{ abbrev: "BS", regex: "/^d{5}$/" },
	{ abbrev: "BH", regex: "/^d{5}$/" },
	{ abbrev: "BD", regex: "/[0-9]{4}/" },
	{ abbrev: "BB", regex: "/BB[0-9]{5}/" },
	{ abbrev: "BY", regex: "/[0-9]{6}/" },
	{ abbrev: "BE", regex: "/[0-9]{4}/" },
	{ abbrev: "BZ", regex: "/^d{5}$/" },
	{ abbrev: "BJ", regex: "/^d{5}$/" },
	{ abbrev: "BM", regex: "/[A-Z]{2}[0-9]{2}/" },
	{ abbrev: "BT", regex: "/[0-9]{5}/" },
	{ abbrev: "BO", regex: "/^d{5}$/" },
	{ abbrev: "BQ", regex: "/^d{5}$/" },
	{ abbrev: "BA", regex: "/[0-9]{5}/" },
	{ abbrev: "BW", regex: "/^d{5}$/" },
	{ abbrev: "BR", regex: "/[0-9]{5}-[0-9]{3}/" },
	{ abbrev: "BN", regex: "/[A-Z]{2}[0-9]{4}/" },
	{ abbrev: "BG", regex: "/[0-9]{4}/" },
	{ abbrev: "BF", regex: "/^d{5}$/" },
	{ abbrev: "BI", regex: "/^d{5}$/" },
	{ abbrev: "KH", regex: "/[0-9]{5}/" },
	{ abbrev: "CM", regex: "/^d{5}$/" },
	{ abbrev: "CA", regex: "/[A-Z][0-9][A-Z] ?[0-9][A-Z][0-9]/" },
	{ abbrev: "CI", regex: "/^d{5}$/" },
	{ abbrev: "CV", regex: "/[0-9]{4}/" },
	{ abbrev: "KY", regex: "/[A-Z]{2}[0-9]-[0-9]{4}/" },
	{ abbrev: "CF", regex: "/^d{5}$/" },
	{ abbrev: "TD", regex: "/^d{5}$/" },
	{ abbrev: "CL", regex: "/[0-9]{7}/" },
	{ abbrev: "CN", regex: "/[0-9]{6}/" },
	{ abbrev: "CO", regex: "/[0-9]{6}/" },
	{ abbrev: "KM", regex: "/^d{5}$/" },
	{ abbrev: "CG", regex: "/^d{5}$/" },
	{ abbrev: "CD", regex: "/^d{5}$/" },
	{ abbrev: "CK", regex: "/^d{5}$/" },
	{ abbrev: "CR", regex: "/[0-9]{5}/" },
	{ abbrev: "HR", regex: "/[0-9]{5}/" },
	{ abbrev: "CU", regex: "/[0-9]{5}/" },
	{ abbrev: "CW", regex: "/^d{5}$/" },
	{ abbrev: "CY", regex: "/[0-9]{4}/" },
	{ abbrev: "CZ", regex: "/[0-9]{3} [0-9]{2}/" },
	{ abbrev: "DK", regex: "/[0-9]{5}/" },
	{ abbrev: "DJ", regex: "/^d{5}$/" },
	{ abbrev: "DM", regex: "/^d{5}$/" },
	{ abbrev: "DO", regex: "/[0-9]{5}/" },
	{ abbrev: "TL", regex: "/^d{5}$/" },
	{ abbrev: "EC", regex: "/[0-9]{6}/" },
	{ abbrev: "EG", regex: "/[0-9]{5}/" },
	{ abbrev: "SV", regex: "/[0-9]{4}/" },
	{ abbrev: "ER", regex: "/^d{5}$/" },
	{ abbrev: "EE", regex: "/[0-9]{5}/" },
	{ abbrev: "ET", regex: "/[0-9]{4}/" },
	{ abbrev: "FK", regex: "/FIQQ 1ZZ/" },
	{ abbrev: "FO", regex: "/[0-9]{3}/" },
	{ abbrev: "FJ", regex: "/^d{5}$/" },
	{ abbrev: "FI", regex: "/[0-9]{5}/" },
	{ abbrev: "FR", regex: "/[0-9]{5}/" },
	{ abbrev: "PF", regex: "/[0-9]{5}/" },
	{ abbrev: "GA", regex: "/^d{5}$/" },
	{ abbrev: "GM", regex: "/^d{5}$/" },
	{ abbrev: "GE", regex: "/^d{5}$/" },
	{ abbrev: "DE", regex: "/[0-9]{5}/" },
	{ abbrev: "GH", regex: "/^d{5}$/" },
	{ abbrev: "GI", regex: "/GX11 1AA/" },
	{ abbrev: "GR", regex: "/[0-9]{3} [0-9]{2}/" },
	{ abbrev: "GL", regex: "/[0-9]{4}/" },
	{ abbrev: "GD", regex: "/^d{5}$/" },
	{ abbrev: "GP", regex: "/971[0-9]{2}/" },
	{ abbrev: "GU", regex: "/d{5}(?:[-s]d{4})?/" },
	{ abbrev: "GT", regex: "/[0-9]{5}/" },
	{
		abbrev: "GG",
		regex:
			"/([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1},2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1},2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))s?[0-9][A-Za-z]{2})/",
	},
	{ abbrev: "GW", regex: "/[0-9]{4}/" },
	{ abbrev: "GQ", regex: "/^d{5}$/" },
	{ abbrev: "GN", regex: "/[0-9]{3}/" },
	{ abbrev: "GY", regex: "/^d{5}$/" },
	{ abbrev: "GF", regex: "/973[0-9]{2}/" },
	{ abbrev: "HT", regex: "/[0-9]{4}/" },
	{ abbrev: "HN", regex: "/[0-9]{5}/" },
	{ abbrev: "HK", regex: "/^d{5}$/" },
	{ abbrev: "HU", regex: "/[0-9]{4}/" },
	{ abbrev: "IS", regex: "/[0-9]{3}/" },
	{ abbrev: "IN", regex: "/[1-9][0-9]{5}/" },
	{ abbrev: "ID", regex: "/[0-9]{5}/" },
	{ abbrev: "IR", regex: "/[0-9]{5}/" },
	{ abbrev: "IQ", regex: "/[0-9]{5}/" },
	{
		abbrev: "IE",
		regex: "/(?:^[AC-FHKNPRTV-Y][0-9]{2}|D6W)[ -]?[0-9AC-FHKNPRTV-Y]{4}$/",
	},
	{ abbrev: "IL", regex: "/[0-9]{5}|[0-9]{7}/" },
	{ abbrev: "IT", regex: "/[0-9]{5}/" },
	{ abbrev: "JM", regex: "/^d{5}$/" },
	{ abbrev: "JP", regex: "/[0-9]{3}-[0-9]{4}/" },
	{
		abbrev: "JE",
		regex:
			"/([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1},2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1},2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))s?[0-9][A-Za-z]{2})/",
	},
	{ abbrev: "JO", regex: "/[0-9]{5}/" },
	{ abbrev: "KZ", regex: "/[0-9]{6}/" },
	{ abbrev: "KE", regex: "/[0-9]{5}/" },
	{ abbrev: "KI", regex: "/^d{5}$/" },
	{ abbrev: "KR", regex: "/[0-9]{5}/" },
	{ abbrev: "KP", regex: "/^d{5}$/" },
	{ abbrev: "XK", regex: "/[0-9]{5}/" },
	{ abbrev: "KW", regex: "/[0-9]{5}/" },
	{ abbrev: "KG", regex: "/[0-9]{6}/" },
	{ abbrev: "LA", regex: "/[0-9]{5}/" },
	{ abbrev: "LV", regex: "/LV-[0-9]{4}/" },
	{ abbrev: "LB", regex: "/[0-9]{4} [0-9]{4}/" },
	{ abbrev: "LS", regex: "/[0-9]{3}/" },
	{ abbrev: "LR", regex: "/[0-9]{4}/" },
	{ abbrev: "LY", regex: "/^d{5}$/" },
	{ abbrev: "LI", regex: "/[0-9]{4}/" },
	{ abbrev: "LT", regex: "/LT-[0-9]{5}/" },
	{ abbrev: "LU", regex: "/[0-9]{4}/" },
	{ abbrev: "MO", regex: "/^d{5}$/" },
	{ abbrev: "MK", regex: "/[0-9]{4}/" },
	{ abbrev: "MG", regex: "/[0-9]{3}/" },
	{ abbrev: "MW", regex: "/^d{5}$/" },
	{ abbrev: "MY", regex: "/[0-9]{5}/" },
	{ abbrev: "MV", regex: "/[0-9]{5}/" },
	{ abbrev: "ML", regex: "/^d{5}$/" },
	{ abbrev: "MT", regex: "/[A-Z]{3} [0-9]{4}/" },
	{ abbrev: "MH", regex: "/d{5}(?:[-s]d{4})?/" },
	{ abbrev: "MQ", regex: "/972[0-9]{2}/" },
	{ abbrev: "MR", regex: "/^d{5}$/" },
	{ abbrev: "MU", regex: "/[0-9]{5}/" },
	{ abbrev: "YT", regex: "/976[0-9]{2}/" },
	{ abbrev: "MX", regex: "/[0-9]{5}/" },
	{ abbrev: "MD", regex: "/MD-?[0-9]{4}/" },
	{ abbrev: "MC", regex: "/980[0-9]{2}/" },
	{ abbrev: "MN", regex: "/[0-9]{5}/" },
	{ abbrev: "ME", regex: "/[0-9]{5}/" },
	{ abbrev: "MS", regex: "/MSR [0-9]{4}/" },
	{ abbrev: "MA", regex: "/[0-9]{5}/" },
	{ abbrev: "MZ", regex: "/[0-9]{4}/" },
	{ abbrev: "MM", regex: "/[0-9]{5}/" },
	{ abbrev: "NA", regex: "/^d{5}$/" },
	{ abbrev: "NR", regex: "/^d{5}$/" },
	{ abbrev: "NP", regex: "/[0-9]{5}/" },
	{ abbrev: "NL", regex: "/(?:NL-)?(d{4})s*([A-Z]{2})/" },
	{ abbrev: "NC", regex: "/988[0-9]{2}/" },
	{ abbrev: "NZ", regex: "/[0-9]{4}/" },
	{ abbrev: "NI", regex: "/^d{5}$/" },
	{ abbrev: "NE", regex: "/[0-9]{4}/" },
	{ abbrev: "NG", regex: "/[0-9]{6}/" },
	{ abbrev: "NU", regex: "/^d{5}$/" },
	{ abbrev: "MP", regex: "/96950/" },
	{ abbrev: "NO", regex: "/[0-9]{4}/" },
	{ abbrev: "OM", regex: "/[0-9]{3}/" },
	{ abbrev: "PK", regex: "/[0-9]{5}/" },
	{ abbrev: "PW", regex: "/d{5}(?:[-s]d{4})?/" },
	{ abbrev: "PA", regex: "/[0-9]{4}/" },
	{ abbrev: "PG", regex: "/[0-9]{3}/" },
	{ abbrev: "PY", regex: "/[0-9]{4}/" },
	{ abbrev: "PE", regex: "/[0-9]{5}/" },
	{ abbrev: "PH", regex: "/[0-9]{4}/" },
	{ abbrev: "PL", regex: "/[0-9]{2}-[0-9]{3}/" },
	{ abbrev: "PT", regex: "/[0-9]{4}-[0-9]{3}/" },
	{ abbrev: "PR", regex: "/d{5}(?:[-s]d{4})?/" },
	{ abbrev: "QA", regex: "/^d{5}$/" },
	{ abbrev: "RE", regex: "/974[0-9]{2}/" },
	{ abbrev: "RO", regex: "/[0-9]{6}/" },
	{ abbrev: "RU", regex: "/[0-9]{6}/" },
	{ abbrev: "RW", regex: "/^d{5}$/" },
	{ abbrev: "WS", regex: "/WS[0-9]{4}/" },
	{ abbrev: "ST", regex: "/^d{5}$/" },
	{ abbrev: "SA", regex: "/[0-9]{5}(-[0-9]{4})?/" },
	{ abbrev: "SN", regex: "/[0-9]{5}/" },
	{ abbrev: "RS", regex: "/[0-9]{5}/" },
	{ abbrev: "SC", regex: "/^d{5}$/" },
	{ abbrev: "SL", regex: "/^d{5}$/" },
	{ abbrev: "SG", regex: "/[0-9]{6}/" },
	{ abbrev: "SK", regex: "/[0-9]{3} [0-9]{2}/" },
	{ abbrev: "SI", regex: "/[0-9]{4}/" },
	{ abbrev: "SB", regex: "/^d{5}$/" },
	{ abbrev: "SO", regex: "/[A-Z]{2} [0-9]{5}/" },
	{ abbrev: "ZA", regex: "/[0-9]{4}/" },
	{ abbrev: "SS", regex: "/^d{5}$/" },
	{ abbrev: "ES", regex: "/[0-9]{5}/" },
	{ abbrev: "LK", regex: "/[0-9]{4}/" },
	{ abbrev: "BL", regex: "/[0-9]{5}/" },
	{ abbrev: "VI", regex: "/d{5}(?:[-s]d{4})?/" },
	{ abbrev: "SE", regex: "/[0-9]{3} [0-9]{2}/" },
	{ abbrev: "SH", regex: "/STHL 1ZZ/" },
	{ abbrev: "KN", regex: "/[A-Z]{2}[0-9]{4}/" },
	{ abbrev: "LC", regex: "/[A-Z]{2}[0-9]{2} [0-9]{3}/" },
	{ abbrev: "SX", regex: "/^d{5}$/" },
	{ abbrev: "VC", regex: "/VC[0-9]{4}/" },
	{ abbrev: "SD", regex: "/[0-9]{5}/" },
	{ abbrev: "SR", regex: "/^d{5}$/" },
	{ abbrev: "SZ", regex: "/[A-Z]{1}[0-9]{3}/" },
	{ abbrev: "CH", regex: "/[0-9]{4}/" },
	{ abbrev: "SY", regex: "/^d{5}$/" },
	{ abbrev: "TW", regex: "/[0-9]{3}(-[0-9]{2})?/" },
	{ abbrev: "TZ", regex: "/[0-9]{5}/" },
	{ abbrev: "TH", regex: "/[0-9]{5}/" },
	{ abbrev: "TG", regex: "/^d{5}$/" },
	{ abbrev: "TO", regex: "/^d{5}$/" },
	{ abbrev: "VG", regex: "/VG[0-9]{4}/" },
	{ abbrev: "TT", regex: "/[0-9]{6}/" },
	{ abbrev: "TN", regex: "/[0-9]{4}/" },
	{ abbrev: "TR", regex: "/[0-9]{5}/" },
	{ abbrev: "TM", regex: "/[0-9]{6}/" },
	{ abbrev: "TC", regex: "/TKCA 1ZZ/" },
	{ abbrev: "TV", regex: "/^d{5}$/" },
	{ abbrev: "UG", regex: "/^d{5}$/" },
	{ abbrev: "UA", regex: "/[0-9]{5}/" },
	{ abbrev: "AE", regex: "/^d{5}$/" },
	{
		abbrev: "GB",
		regex:
			"/([Gg][Ii][Rr] 0[Aa]{2})|((([A-Za-z][0-9]{1},2})|(([A-Za-z][A-Ha-hJ-Yj-y][0-9]{1},2})|(([A-Za-z][0-9][A-Za-z])|([A-Za-z][A-Ha-hJ-Yj-y][0-9][A-Za-z]?))))s?[0-9][A-Za-z]{2})/",
	},
	{ abbrev: "US", regex: "/d{5}(?:[-s]d{4})?/" },
	{ abbrev: "UY", regex: "/[0-9]{5}/" },
	{ abbrev: "UZ", regex: "/[0-9]{6}/" },
	{ abbrev: "VU", regex: "/^d{5}$/" },
	{ abbrev: "VE", regex: "/[0-9]{4}(-[A-Z]{1})?/" },
	{ abbrev: "VN", regex: "/[0-9]{6}/" },
	{ abbrev: "YE", regex: "/^d{5}$/" },
	{ abbrev: "ZM", regex: "/[0-9]{5}/" },
	{ abbrev: "ZW", regex: "/^d{5}$/" },
];
